# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
config.vm.define "nagiosServer" do |nagiosServer|
nagiosServer.vm.hostname = "nagiosServer.rnstech.com"
nagiosServer.vm.box = "ubuntu/trusty64"
nagiosServer.vm.box_url = "ubuntu/trusty64"

nagiosServer.vm.network :private_network,
      ip: '192.168.56.65',
      netmask: '255.255.255.0'
  # manual ipv6
end

config.vm.define "nagiosClient" do |nagiosClient|

nagiosClient.vm.hostname = "nagiosClient.rnstech.com"
nagiosClient.vm.box = "ubuntu/trusty64"
nagiosClient.vm.box_url = "ubuntu/trusty64"

nagiosClient.vm.network :private_network,
      ip: '192.168.56.66',
      netmask: '255.255.255.0'
end
end